# Generated by Django 4.0.3 on 2022-04-06 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='assigned_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
