# Generated by Django 4.0.3 on 2022-04-15 09:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankloan',
            name='principal',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(500000)]),
        ),
        migrations.AlterField(
            model_name='bankloan',
            name='principal_remainder',
            field=models.FloatField(default=models.FloatField(validators=[django.core.validators.MaxValueValidator(500000)])),
        ),
    ]
