# Generated by Django 4.0.3 on 2022-04-15 11:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_manager', '0002_alter_bankloan_principal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankloan',
            name='duration_in_years',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='bankloan',
            name='principal',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(500000), django.core.validators.MinValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='bankloan',
            name='principal_remainder',
            field=models.FloatField(default=models.FloatField(validators=[django.core.validators.MaxValueValidator(500000), django.core.validators.MinValueValidator(1000)])),
        ),
    ]
