# Generated by Django 4.0.3 on 2022-04-13 13:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_manager', '0002_rename_customer_individualcustomer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(choices=[('BGN', 'BGN'), ('USD', 'USD'), ('CHF', 'CHF'), ('GBP', 'GBP'), ('JPY', 'JPY'), ('EUR', 'EUR')], max_length=40),
        ),
        migrations.AlterField(
            model_name='bankloan',
            name='currency',
            field=models.CharField(choices=[('BGN', 'BGN')], max_length=40),
        ),
        migrations.AlterField(
            model_name='bankloan',
            name='duration_in_months',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(360)]),
        ),
    ]
