# Generated by Django 4.0.3 on 2022-04-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_manager', '0002_alter_customer_assigned_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='debit_card',
            field=models.CharField(choices=[('VISA', 'VISA'), ('MASTERCARD', 'MASTERCARD')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='available_balance',
            field=models.FloatField(default=0),
        ),
    ]
