# Generated by Django 4.0.3 on 2022-04-15 17:18

import BankOfSoftUni.helpers.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_manager', '0003_alter_bankloan_duration_in_years_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualcustomer',
            name='first_name',
            field=models.CharField(max_length=40, validators=[BankOfSoftUni.helpers.validators.validate_only_letters]),
        ),
    ]
