# Generated by Django 4.0.3 on 2022-04-13 16:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_manager', '0003_alter_account_currency_alter_bankloan_currency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankloan',
            old_name='monthly_payment_due_date',
            new_name='next_monthly_payment_due_date',
        ),
        migrations.RemoveField(
            model_name='bankloan',
            name='duration_in_months',
        ),
        migrations.AddField(
            model_name='bankloan',
            name='duration_in_years',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(30)]),
            preserve_default=False,
        ),
    ]
