# Generated by Django 4.0.3 on 2022-04-08 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_manager', '0004_account_assigned_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='customer_accounts', to='customer_manager.customer'),
        ),
    ]
