# Generated by Django 4.0.3 on 2022-04-15 17:20

import BankOfSoftUni.helpers.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_manager', '0004_alter_individualcustomer_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualcustomer',
            name='last_name',
            field=models.CharField(max_length=40, validators=[BankOfSoftUni.helpers.validators.validate_only_letters]),
        ),
        migrations.AlterField(
            model_name='individualcustomer',
            name='occupation',
            field=models.CharField(blank=True, default='unemployed', max_length=40, null=True, validators=[BankOfSoftUni.helpers.validators.validate_only_letters]),
        ),
        migrations.AlterField(
            model_name='individualcustomer',
            name='sir_name',
            field=models.CharField(blank=True, max_length=40, null=True, validators=[BankOfSoftUni.helpers.validators.validate_only_letters]),
        ),
        migrations.AlterField(
            model_name='individualcustomer',
            name='ucn',
            field=models.BigIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
