# Generated by Django 4.0.3 on 2022-04-19 19:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_manager', '0005_alter_individualcustomer_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankloan',
            name='duration_in_years',
        ),
        migrations.AddField(
            model_name='bankloan',
            name='duration_in_months',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(360), django.core.validators.MinValueValidator(12)]),
            preserve_default=False,
        ),
    ]
