# Generated by Django 4.0.3 on 2022-03-27 20:15

import BankOfSoftUni.helpers.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('first_name', models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(2), BankOfSoftUni.helpers.validators.validate_only_letters])),
                ('last_name', models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(2), BankOfSoftUni.helpers.validators.validate_only_letters])),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_images', validators=[BankOfSoftUni.helpers.validators.MaxFileSizeInMbValidator(5)])),
                ('employee_role', models.CharField(choices=[('Cashier', 'Cashier'), ('Credit consultant', 'Credit consultant'), ('Branch manager', 'Branch manager')], max_length=17)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
