# Generated by Django 4.0.3 on 2022-04-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='bankuser',
            name='is_superuser',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=5),
        ),
    ]
