# Generated by Django 4.0.3 on 2022-04-15 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_alter_profile_employee_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='employee_role',
            field=models.CharField(choices=[('Trainee', 'Trainee'), ('Cashier', 'Cashier'), ('Credit consultant', 'Credit consultant'), ('Branch manager', 'Branch manager'), ('Moderator', 'Moderator'), ('ADMINISTRATOR', 'ADMINISTRATOR')], max_length=17),
        ),
    ]
