# Generated by Django 4.0.3 on 2022-04-15 08:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnnualTargets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_clients_target', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('registered_clients_actual', models.IntegerField(blank=True, default=0, null=True)),
                ('opened_accounts_target', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('opened_accounts_actual', models.IntegerField(blank=True, default=0, null=True)),
                ('opened_loans_count_target', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('opened_loans_actual', models.IntegerField(blank=True, default=0, null=True)),
                ('total_loans_size_target', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('total_loans_size_actual', models.FloatField(blank=True, default=0, null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth_app.profile')),
            ],
        ),
    ]
