# Generated by Django 4.0.3 on 2022-04-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertask',
            name='task_type1',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
