# Generated by Django 4.0.3 on 2022-04-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0002_usertask_task_type1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertask',
            name='task_type1',
        ),
        migrations.AlterField(
            model_name='usertask',
            name='task_type',
            field=models.CharField(choices=[('Register new client', 'Register new client'), ('Open new account', 'Open new account'), ('Open new loan', 'Open new loan')], max_length=30),
        ),
    ]
