# Generated by Django 4.0.3 on 2022-04-14 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_alter_profile_employee_role'),
        ('tasks_app', '0002_rename_task_result_usertask_result_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userannualtargets',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.profile', unique=True),
        ),
    ]
